//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGTIT.Checador
{
    using System;
    using System.Collections.Generic;
    
    public partial class AREA
    {
        public int IDAREA { get; set; }
        public string CVEAREA { get; set; }
        public string AREA1 { get; set; }
        public short IDMUNICIPIO { get; set; }
        public bool SUBPROCURADURIA { get; set; }
        public byte IDDIRECCION { get; set; }
        public bool BAJA { get; set; }
        public bool BODEGAARMA { get; set; }
        public Nullable<short> IDRESPONSABLEBODEGA { get; set; }
        public byte IDTIPOAREA { get; set; }
        public string TELEFONO { get; set; }
        public string DIRECCION { get; set; }
        public bool SECUESTROS { get; set; }
    }
}
