//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGTIT.Checador
{
    using System;
    using System.Collections.Generic;
    
    public partial class employees_respaldo
    {
        public int id { get; set; }
        public long general_direction_id { get; set; }
        public long direction_id { get; set; }
        public long subdirectorate_id { get; set; }
        public long department_id { get; set; }
        public Nullable<int> plantilla_id { get; set; }
        public string name { get; set; }
        public string photo { get; set; }
        public byte[] fingerprint { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> status_id { get; set; }
    }
}
