//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGTIT.Checador
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public Nullable<int> IDAREA { get; set; }
        public short IDEMPLEADO { get; set; }
        public byte IDESTADOEMPLEADO { get; set; }
        public Nullable<int> NUMEMP { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDO { get; set; }
        public string APELLIDOPATERNO { get; set; }
        public string APELLIDOMATERNO { get; set; }
        public Nullable<System.DateTime> FECHABAJA { get; set; }
        public string MOTIVOBAJA { get; set; }
        public byte IDMOTIVOBAJA { get; set; }
        public byte IDSEXO { get; set; }
        public byte[] FOTO { get; set; }
        public Nullable<System.DateTime> FECHA_NAC { get; set; }
        public string RFC { get; set; }
        public Nullable<System.DateTime> FECHA_ALTA { get; set; }
        public string DOMICILIO { get; set; }
        public short IDPLAZA { get; set; }
        public byte IDESTADOCIVIL { get; set; }
        public short IDPROFESION { get; set; }
        public byte IDNACIONALIDAD { get; set; }
        public string CURP { get; set; }
        public string CUIP { get; set; }
        public short IDESTADO { get; set; }
        public short IDMUNICIPIO { get; set; }
        public string COLONIA { get; set; }
        public string CALLE { get; set; }
        public string NUMERO { get; set; }
        public string CP { get; set; }
        public string TELEFONO { get; set; }
        public string EXTENCION { get; set; }
        public string EMAIL { get; set; }
        public string LUGARNAC { get; set; }
        public bool TITULADO { get; set; }
        public string CEDULAPROF { get; set; }
        public bool SM { get; set; }
        public byte[] FIRMA { get; set; }
        public byte[] HDD { get; set; }
        public byte[] HDI { get; set; }
        public string CHDD { get; set; }
        public string CHDI { get; set; }
        public Nullable<System.DateTime> FECHAREGISTROCLINICA { get; set; }
        public Nullable<System.DateTime> FECHAREGISTROAREA { get; set; }
        public Nullable<System.DateTime> FECHAREGISTROPLAZA { get; set; }
        public short IDCLINICA { get; set; }
        public string TIPOSANGRE { get; set; }
        public string ALERGIA { get; set; }
        public string CARTILLASMN { get; set; }
        public bool CARTILLALIBERADA { get; set; }
        public string CARTILLACLASE { get; set; }
        public string CARTILLAOBSERVACIONES { get; set; }
        public string OBSERVACIONES { get; set; }
        public Nullable<System.DateTime> FECHAFOTO { get; set; }
        public Nullable<int> ID_UBICACION_FISICA { get; set; }
        public bool COMISION { get; set; }
        public string OFICIOCOMISION { get; set; }
        public Nullable<System.DateTime> FECHAOFICIOCOMISION { get; set; }
        public string CUENTABANCARIA { get; set; }
        public string CLABEINTERBANCARIA { get; set; }
        public string LOCALIZACION { get; set; }
        public Nullable<int> EDAD { get; set; }
        public Nullable<int> ANTIGUEDAD { get; set; }
        public string CEDULATEST { get; set; }
        public Nullable<short> ID_TIPO_SERVICIO_MEDICO { get; set; }
        public string NSS { get; set; }
        public Nullable<byte> IDTIPOSANGRE { get; set; }
        public Nullable<int> DIAS_ACUM { get; set; }
        public Nullable<short> IDRADICACION { get; set; }
        public Nullable<byte> IDDEPARTAMENTO { get; set; }
        public Nullable<bool> CARTILLA { get; set; }
        public Nullable<bool> CARTANOA { get; set; }
        public Nullable<bool> ANTIDOPING { get; set; }
        public Nullable<bool> EXAMENMEDICO { get; set; }
        public Nullable<bool> CONSTANCIA { get; set; }
        public Nullable<bool> EXAMEN_CONFIANZA { get; set; }
        public Nullable<System.DateTime> FECHARECEPCION { get; set; }
        public string OBSLICENCIA { get; set; }
        public string OFICIOLICENCIA { get; set; }
        public Nullable<System.DateTime> FECHAEXPEDICION { get; set; }
        public Nullable<System.DateTime> FECHAACEPTACION { get; set; }
        public Nullable<bool> FECHARECEPCIONVALIDA { get; set; }
        public Nullable<bool> FECHAEXPEDICIONVALIDA { get; set; }
        public Nullable<bool> FECHAACEPTACIONVALIDA { get; set; }
        public string INICIALES { get; set; }
        public Nullable<bool> LICENCIAMANEJO { get; set; }
        public string FOLIOLM { get; set; }
        public Nullable<System.DateTime> FECHAEXPLM { get; set; }
        public Nullable<System.DateTime> FECHAVENLM { get; set; }
        public short IDHISTORICO_PLAZA_EMPLEADO { get; set; }
        public short IDHISTORICO_AREA_EMPLEADO { get; set; }
        public Nullable<bool> MILITAR { get; set; }
        public bool HABILITADO { get; set; }
        public short IDPUESTOHABILITADO { get; set; }
        public string TARJETA { get; set; }
        public Nullable<bool> RADICADO { get; set; }
        public Nullable<short> IdBanco { get; set; }
        public Nullable<short> ID_LICENCIA { get; set; }
        public string OFICIO_LICENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_LICENCIA { get; set; }
        public Nullable<bool> FECHA_LICENCIA_VALIDA { get; set; }
        public string OFICIO_ENVIADO_SEDENA { get; set; }
        public Nullable<System.DateTime> FECHA_ENVIADO_SEDENA { get; set; }
        public Nullable<bool> FECHA_ENVIADO_SEDENA_VALIDA { get; set; }
        public string OFICIO_AUTORIZA_SEDENA { get; set; }
        public Nullable<System.DateTime> FECHA_AUTORIZA_SEDENA { get; set; }
        public Nullable<bool> FECHA_AUTORIZA_SEDENA_VALIDA { get; set; }
        public string OFICIO_INCORPORACION { get; set; }
        public Nullable<System.DateTime> FECHA_INCORPORACION { get; set; }
        public Nullable<bool> FECHA_INCORPORACION_VALIDA { get; set; }
        public string OFICIO_VINCULACION { get; set; }
        public Nullable<System.DateTime> FECHA_VINCULACION { get; set; }
        public Nullable<bool> FECHA_VINCULACION_VALIDA { get; set; }
        public string OFICIO_CONTESTACION_VINCULACION { get; set; }
        public Nullable<System.DateTime> FECHA_CONTESTACION_VICULACION { get; set; }
        public Nullable<bool> FECHA_CONTESTACION_VICULACION_VALIDA { get; set; }
        public Nullable<bool> SABEMANEJAR { get; set; }
        public Nullable<System.DateTime> FECHAAGUINALDO { get; set; }
        public Nullable<System.DateTime> FECHAQUINQUENIO { get; set; }
        public Nullable<bool> QUINQUENIO { get; set; }
        public Nullable<bool> Ayuda_postuma { get; set; }
        public Nullable<bool> LICENCIACOLECTIVA { get; set; }
        public Nullable<System.DateTime> FECHALICCOLECTIVA { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO_GOB { get; set; }
        public Nullable<int> IdMunicipioRadicacion { get; set; }
        public string CELULAR { get; set; }
        public string NUMIPSSET { get; set; }
        public string NUMSICNO { get; set; }
    }
}
