//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGTIT.Checador
{
    using System;
    using System.Collections.Generic;
    
    public partial class failed_jobs
    {
        public long id { get; set; }
        public string uuid { get; set; }
        public string connection { get; set; }
        public string queue { get; set; }
        public string payload { get; set; }
        public string exception { get; set; }
        public System.DateTime failed_at { get; set; }
    }
}
