//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGTIT.Checador
{
    using System;
    using System.Collections.Generic;
    
    public partial class incident
    {
        public int id { get; set; }
        public int employee_id { get; set; }
        public int incident_type_id { get; set; }
        public int incident_state_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual incident_states incident_states { get; set; }
        public virtual incident_types incident_types { get; set; }
    }
}
