//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGTIT.Checador
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UsuariosDBEntities : DbContext
    {
        public UsuariosDBEntities()
            : base("name=UsuariosDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CntrlDeAsistencia> CntrlDeAsistencias { get; set; }
        public virtual DbSet<ControlDeAsistencia> ControlDeAsistencias { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<direction> directions { get; set; }
        public virtual DbSet<EmpleadoRegistro> EmpleadoRegistroes { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<employees_respaldo> employees_respaldo { get; set; }
        public virtual DbSet<failed_jobs> failed_jobs { get; set; }
        public virtual DbSet<general_directions> general_directions { get; set; }
        public virtual DbSet<incident_states> incident_states { get; set; }
        public virtual DbSet<incident_types> incident_types { get; set; }
        public virtual DbSet<incident> incidents { get; set; }
        public virtual DbSet<menu_user> menu_user { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<migration> migrations { get; set; }
        public virtual DbSet<record> records { get; set; }
        public virtual DbSet<subdirectorate> subdirectorates { get; set; }
        public virtual DbSet<type_files> type_files { get; set; }
        public virtual DbSet<type_justifies> type_justifies { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<working_hours> working_hours { get; set; }
        public virtual DbSet<file> files { get; set; }
        public virtual DbSet<justify> justifies { get; set; }
        public virtual DbSet<password_resets> password_resets { get; set; }
        public virtual DbSet<Vw_plazas_nomina> Vw_plazas_nomina { get; set; }
        public virtual DbSet<VwEmpleadoRegistro> VwEmpleadoRegistroes { get; set; }
    }
}
