//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGTIT.Checador
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UsuariosDBEntities : DbContext
    {
        public UsuariosDBEntities()
            : base("name=UsuariosDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<direction> directions { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<general_directions> general_directions { get; set; }
        public virtual DbSet<incident_states> incident_states { get; set; }
        public virtual DbSet<incident_types> incident_types { get; set; }
        public virtual DbSet<incident> incidents { get; set; }
        public virtual DbSet<record> records { get; set; }
        public virtual DbSet<subdirectorate> subdirectorates { get; set; }
        public virtual DbSet<type_files> type_files { get; set; }
        public virtual DbSet<type_justifies> type_justifies { get; set; }
        public virtual DbSet<working_hours> working_hours { get; set; }
        public virtual DbSet<justify> justifies { get; set; }
        public virtual DbSet<notification> notifications { get; set; }
        public virtual DbSet<working_days> working_days { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<clientsStatusLog> clientsStatusLogs { get; set; }
    }
}
