//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGTIT.Checador
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_plazas_nomina
    {
        public byte id_tipo_nomina { get; set; }
        public int id_plantilla { get; set; }
        public int num_plaza { get; set; }
        public short id_categoria { get; set; }
        public Nullable<short> efiscal { get; set; }
        public Nullable<short> id_uejecutora { get; set; }
        public byte id_tipo_contrato_nomina { get; set; }
        public Nullable<System.DateTime> fec_fin { get; set; }
        public short id_status_plaza { get; set; }
        public Nullable<short> id_status_plantilla { get; set; }
        public Nullable<System.DateTime> Fec_Asignacion { get; set; }
        public Nullable<System.DateTime> Fec_Ingreso { get; set; }
        public string Id_Division_Nomina { get; set; }
        public string txt_division_nomina { get; set; }
        public Nullable<int> Id_Depto_Nomina { get; set; }
        public string txt_depto_nomina { get; set; }
        public string Nombre { get; set; }
    }
}
