//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGTIT.Checador
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwEmpleadoRegistro
    {
        public int idEmpleadoRegistro { get; set; }
        public string NombreCompleto { get; set; }
        public Nullable<int> IdPlantilla { get; set; }
        public string DepartamentoNomina { get; set; }
        public byte[] Huella { get; set; }
        public string HORA1 { get; set; }
        public string HORA2 { get; set; }
        public string HORA3 { get; set; }
        public string HORA4 { get; set; }
        public int QUEBRADO { get; set; }
    }
}
