//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGTIT.Checador
{
    using System;
    using System.Collections.Generic;
    
    public partial class working_hours
    {
        public int id { get; set; }
        public int employee_id_ { get; set; }
        public string checkin { get; set; }
        public string toeat { get; set; }
        public string toarrive { get; set; }
        public string checkout { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
