//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DGTIT.Checador
{
    using System;
    using System.Collections.Generic;
    
    public partial class working_days
    {
        public int id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<bool> week { get; set; }
        public Nullable<bool> weekend { get; set; }
        public Nullable<int> holidays { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    }
}
